spring:
  mail:
    host: smtp.163.com
    port: 465
    username: jonnyou1012@163.com
    password: LUrKeZM7eVCaEv9D
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

server:
  port: 9090

mail:
  to: 1647063649@qq.com,3389257585@qq.com
